version: "3"
services: 
    api:
        container_name: property-value-api
        image: node:12
        working_dir: /usr/src/property-value-api
        restart: always
        command: bash -c "npm install --only=prod && npm run debug"
        volumes: 
            - ./dist/:/usr/src/property-value-api/dist
            - ./package.json:/usr/src/property-value-api/package.json
        ports: 
            - "5050:5050"
            - "9222:9222"
